"""a

Revision ID: 16bd181c2ae8
Revises: 
Create Date: 2023-10-25 21:38:14.032502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16bd181c2ae8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_allocation', schema=None) as batch_op:
        batch_op.drop_column('resource_name')

    # ### end Alembic commands ###
